import {
    CallHandler,
    ExecutionContext,
    Injectable,
    NestInterceptor,
} from '@nestjs/common';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class ResponseInterceptor implements NestInterceptor {
    intercept(
        context: ExecutionContext,
        next: CallHandler,
    ): Observable<any> {
        return next.handle().pipe(
            map((data: any) => ({
                success: true,
                statusCode: context.switchToHttp().getResponse().statusCode,
                message: 'Request successful',
                data,
            })),
        );
    }
}







//  Viewed package.json:1-50
// Listed directory urlshortner
// Viewed tsconfig.json:1-24
// Viewed response.interceptor.ts:1-25
// Listed directory api
// Listed directory node_modules
// Viewed pnpm-workspace.yaml:1-4
// Viewed package.json:1-30
// Viewed pnpm-lock.yaml:1-50
// Viewed TURBOREPO_GUIDE.md:1-60

// ### What Does This Error Mean?

// When TypeScript reports:
// > **"Cannot find module '@nestjs/common' or its corresponding type declarations."** (TS2307)

// it means TypeScript's module resolution algorithm was told to import from `'@nestjs/common'` in [response.interceptor.ts](file:///Users/mohitkumar/Desktop/urlshortner/apps/api/src/common/interceptors/response.interceptor.ts#L6), but when it traversed the filesystem looking for the package's files or type definitions (`.d.ts`), **it found nothing on disk**.

// ---

// ### Why Is This Happening Here?

// Listing a package in [apps/api/package.json](file:///Users/mohitkumar/Desktop/urlshortner/apps/api/package.json#L25) defines your **intent** to use that dependency, but TypeScript doesn't read the dependency list directly to resolve code — it looks into `node_modules` based on the settings in [tsconfig.json](file:///Users/mohitkumar/Desktop/urlshortner/apps/api/tsconfig.json).

// If you look closely at your workspace state:

// 1. **Missing `node_modules`**: The `apps/api/` directory currently does not have a `node_modules/` folder.
// 2. **Lockfile state**: In [pnpm-lock.yaml](file:///Users/mohitkumar/Desktop/urlshortner/pnpm-lock.yaml#L18), the entry for `apps/api` is still empty:
//    ```yaml
//    apps/api: {}
//    ```
// 3. **Competing package managers**: Notice there is both a [pnpm-lock.yaml](file:///Users/mohitkumar/Desktop/urlshortner/pnpm-lock.yaml) and a [package-lock.json](file:///Users/mohitkumar/Desktop/urlshortner/apps/api/package-lock.json) in your project.

// Because the dependencies listed in `apps/api/package.json` were never installed or linked into the monorepo's dependency tree, TypeScript cannot locate the `@nestjs/common` package.

// ---

// ### Questions to Guide Your Fix

// To resolve this and keep your monorepo clean, explore these questions:

// 1. **Which package manager is the single source of truth for this workspace?**
//    - Check the `"packageManager"` field in the root [package.json](file:///Users/mohitkumar/Desktop/urlshortner/package.json#L14) and the [pnpm-workspace.yaml](file:///Users/mohitkumar/Desktop/urlshortner/pnpm-workspace.yaml) file.
//    - If the project is configured for `pnpm`, what should you do with stray `package-lock.json` files generated by `npm`?

// 2. **How do you install dependencies across a monorepo?**
//    - In a monorepo (Turborepo + pnpm workspaces), where should you run the install command? (At the monorepo root or inside individual sub-packages?)
//    - Once you run the install command with your workspace package manager, what changes do you expect to see in [pnpm-lock.yaml](file:///Users/mohitkumar/Desktop/urlshortner/pnpm-lock.yaml) and `node_modules`?

// Have you already tried running an install command, or did you hit any errors when trying to install dependencies for `apps/api`?